# Generated by Django 3.1.7 on 2021-03-15 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_create_homepage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homepage',
            options={'verbose_name': ' Pagee Accueil', 'verbose_name_plural': 'Pages Accueil'},
        ),
    ]
