# Generated by Django 3.1.7 on 2021-03-15 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20210315_1944'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homepage',
            options={'verbose_name': ' Page Accueil', 'verbose_name_plural': 'Pages Accueil'},
        ),
    ]
